"""Add notes field to Deal

Revision ID: 80d237861e5d
Revises: 642ca3b56a67
Create Date: 2025-07-08 02:40:03.212457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d237861e5d'
down_revision: Union[str, Sequence[str], None] = '642ca3b56a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('notes', sa.String(), nullable=True)
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal', 'notes')
    # ### end Alembic commands ###
