"""Add phone and address to a Client

Revision ID: beb0f7f32d83
Revises: 80d237861e5d
Create Date: 2025-07-08 02:51:52.904946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb0f7f32d83'
down_revision: Union[str, Sequence[str], None] = '80d237861e5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('client', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'address')
    op.drop_column('client', 'phone')
    # ### end Alembic commands ###
