"""Add soft-delete logic for client.

Revision ID: f434cbab5bbf
Revises: beb0f7f32d83
Create Date: 2025-07-08 03:39:53.679270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f434cbab5bbf'
down_revision: Union[str, Sequence[str], None] = 'beb0f7f32d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add is_active with a default value for existing rows
    op.add_column('client', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.create_index(op.f('ix_client_is_active'), 'client', ['is_active'], unique=False)
    # Optionally, remove the server_default after setting values (for future inserts)
    op.alter_column('client', 'is_active', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_is_active'), table_name='client')
    op.drop_column('client', 'is_active')
    # ### end Alembic commands ###
